<html>
<?php include 'adminHead.phtml'; ?>
<body>
<?php include 'adminNavbar.phtml'; ?>
<div class="row add-book-content">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="result-message"><?php echo $result; ?></div>
        <div class="col-xs-12">
            <h3>Edit a book...</h3>
            <h6>*Required fields</h6>
        </div>
        <form action="/adminDashboard/EditBook" id="form" method="post" enctype="multipart/form-data">
            <div class="col-xs-12 col-md-6">
                <h4>Product no:</h4>
                <input type="number" name="productNo" value="<?php echo $bookData['productNo']; ?>" step="1" min="1"
                       required
                       readonly>
                <h4>*Title:</h4>
                <input type="text" class="required-title" name="title" value="<?php echo $bookData['title']; ?>" required>
                <h4>*Author:</h4>
                <input type="text" class="required-author" name="author" value="<?php echo $bookData['author']; ?>" required>
                <h4>*Category:</h4>
                <select class="form-control" name="required-category" required>
                    <?php
                    foreach ($categories as $category) {
                        $selected = '';
                        if ($category['id'] == $bookData['category']) {
                            $selected = 'selected';
                        }
                        ?>
                        <option
                            value="<?php echo $category['id'] ?>"<?php echo $selected; ?>>
                            <?php echo $category['name']; ?>
                        </option>
                        <?php
                    }
                    ?>
                </select>
                <h4>*Description:</h4>
                <textarea type="text" class="required-description" rows="3" name="description"
                          required><?php echo $bookData['description']; ?></textarea>
                <h4>*Format:</h4>
                <select class="form-control" name="format" required>
                    <?php
                    foreach ($formats as $format) {
                        $selected = '';
                        if ($format['id'] == $bookData['format_id']) {
                            $selected = 'selected';
                        }
                        ?>
                        <option value="<?php echo $format['id'] ?>"<?php echo $selected; ?>>
                            <?php echo $format['name'] ?>
                        </option>
                        <?php
                    }
                    ?>
                </select>
                <h4>Year Published:</h4>
                <input type="number" class="yearContent" name="yearPublished" maxlength="4" step="1"
                       value="<?php echo $bookData['year_published']; ?>">
                <h4>Publisher:</h4>
                <input type="text" class="required-publisher" name="publisher" value="<?php echo $bookData['publisher']; ?>">
            </div>
            <div class="col-xs-12 col-md-6">
                <h4>*Cost Price:</h4>
                <input type="number" class="required-cost-price" name="costPrice" min="0.00" maxlength="8" step="0.01"
                       value="<?php echo $bookData['cost_price']; ?>" required>
                <h4>*Sell Price:</h4>
                <input type="number" class="required-sell-price" name="sellPrice" min="0.00" maxlength="8" step="0.01"
                       value="<?php echo $bookData['sell_price']; ?>" required>
                <h4>*Stock Level:</h4>
                <input type="number" class="stockContent" name="stockLevel" min="0" maxlength="5" step="1"
                       value="<?php echo $bookData['stock_level']; ?>" required>

                <div class="no-mobile">
                    <h4>Image:</h4>
                    <h6>Current image: <input type="text" name="existingImage" value="<?php echo $bookData['image']; ?>" readonly></h6>
                    <input type="file" name="image" id="fileToUpload" enctype="multipart/form-data">
                </div>
                <h4>Notes:</h4>
                <textarea type="text" class="required-notes" rows="3" name="notes" value="<?php echo $bookData['notes']; ?>"></textarea>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-md-3 col-md-offset-8">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>
