<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/../img/favicon.ico" type="image/x-icon">
    <title>Bookie Monster</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/adminNavbar.css">
    <link rel="stylesheet" type="text/css" href="/css/adminHome.css">
    <link rel="stylesheet" type="text/css" href="/css/adminAddBook.css">
    <link rel="stylesheet" type="text/css" href="/css/adminEditBookFindBook.css">
    <link rel="stylesheet" type="text/css" href="/css/adminManageFeatured.css">
    <link rel="stylesheet" type="text/css" href="/css/adminCsvUpload.css">
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="/js/validate.js"></script>
    <script src="/js/addBookEditBook.js"></script>
</head>
