<html>
<?php include 'adminHead.phtml'; ?>
<body>
<?php include 'adminNavbar.phtml'; ?>
<div class="row add-book-content">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="result-message"><?php echo $result;?></div>
        <div class="col-xs-12">
            <h3>Add a book...</h3>
            <h6>*Required fields</h6>
        </div>
        <form action="" id="form" method="post" enctype="multipart/form-data">
            <div class="col-xs-12 col-md-6">
                <h4>*Title:</h4>
                <input type="text" class="required-title" name="title" required>
                <h4>*Author:</h4>
                <input type="text" class="required-author" name="author" required>
                <h4>*Category:</h4>
                <select class="form-control required-category" name="category" required>
                    <?php
                    foreach ($categories as $category) {
                    ?>
                    <option value="<?php echo $category['id']; ?>"><?php echo $category['name']; ?></option>
                    <?php
                    }
                    ?>
                </select>
                <h4>*Description:</h4>
                <textarea type="text" class="required-description" rows="3" name="description" required></textarea>
                <h4>*Format:</h4>
                <select class="form-control" name="format" required>
                    <?php
                    foreach ($formats as $format) {
                        ?>
                        <option value="<?php echo $format['id']; ?>"><?php echo $format['name']; ?></option>
                        <?php
                    }
                    ?>
                </select>
                <h4>Year Published:</h4>
                <input type="number" class="yearContent" name="yearPublished" maxlength="4" step="1">
                <h4>Publisher:</h4>
                <input type="text" class="required-publisher" name="publisher">
            </div>
            <div class="col-xs-12 col-md-6">
                <h4>*Cost Price:</h4>
                <input type="number" class="required-cost-price" name="costPrice" min="0.00" maxlength="8" step="0.01" value="0.00" required>
                <h4>*Sell Price:</h4>
                <input type="number" class="required-sell-price" name="sellPrice" min="0.00" maxlength="8" step="0.01" value="0.00" required>
                <h4>*Stock Level:</h4>
                <input type="number" class="stockContent" name="stockLevel" min="0" maxlength="3" step="1" value="1" required>

                <div class="no-mobile">
                    <h4>Image:</h4>
                    <h6>(max 4MB)</h6>
                    <input type="file" name="image" id="fileToUpload" enctype="multipart/form-data">
                </div>
                <h4>Notes:</h4>
                <textarea class="required-notes" type="text" rows="3" name="notes"></textarea>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-md-3 col-md-offset-8">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>
