<html>
<?php include 'shopHead.phtml'; ?>
<body>
<div class="container-fluid">
    <?php include 'shopFrontNavbar.phtml'; ?>
    <div class="col-xs-12 col-md-8 col-md-offset-2 book-product-page">
        <div class="row product-view">
            <div class="col-xs-12 col-md-6">
                <img class="book-image" src="/img/uploadedimg/<?php echo $bookData['image']; ?>">
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="col-xs-12">
                    <h2><?php echo $bookData['title']; ?><h5>(<?php echo $formatName; ?>)</h5></h2>
                    <h5 class="author">by <?php echo $bookData['author']; ?></h5>

                    <h3>Price: &pound;<?php echo $bookData['sell_price']; ?></h3>

                    <div class="col-xs-12 col-md-6 element-spacing paperback format-button">
                        <a href="<?php echo($bookData['format_id'] == 2 ? $bookData['productNo'] : $otherFormatBookId); ?>">
                            <button
                                class="btn btn-primary <?php echo($bookData['format_id'] == 2 ? ' active' : ''); ?>">
                                Paperback
                            </button>
                        </a>
                    </div>
                    <div class="col-xs-12 col-md-6 element-spacing hardback format-button">
                        <a href="<?php echo($bookData['format_id'] == 1 ? $bookData['productNo'] : $otherFormatBookId); ?>">
                            <button class="btn btn-primary<?php echo($bookData['format_id'] == 1 ? ' active' : ''); ?>">
                                Hardcover
                            </button>
                        </a>
                    </div>
                    <form action="" method="post">
                        <div class="element-spacing" <?php echo($availabilityMessage ? 'hidden' : ''); ?>>
                            <div class="maxQtyReachedMsg"><?= $maxQtyReachedMsg; ?></div>
                            <label>Quantity:</label>
                            <input type="number" name="qty" class="stockContent" value="1" min="1" max="<?php echo $bookData['stock_level']; ?>"
                                   step="1" required>
                            <input class="quantity-default" type="number" name="productId"
                                   value="<?php echo $bookData['productNo'] ?>" hidden>
                            <div class="element-spacing">
                                <input type="submit" value="Add To Basket">
                            </div>
                        </div>
                        <div class="element-spacing">
                            <div class="availability-message"><?= $availabilityMessage; ?></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <hr class="divider">
        <div class="row">
            <div class="col-xs-12 col-md-6 product-info">
                <div class="row">
                    <p>Year Published:</p>

                    <p class="product-info-value"><?php echo $bookData['year_published']; ?></p>
                </div>
                <div class="row">
                    <p>Category:</p>

                    <p class="product-info-value"><?php echo $categoryName; ?></p>
                </div>
                <div class="row">
                    <p>Publisher:</p>

                    <p class="product-info-value"><?php echo $bookData['publisher']; ?></p>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 description">
                <h3>Description:</h3>

                <p><?php echo $bookData['description']; ?></p>
            </div>
        </div>
    </div>
</div>
</body>
</html>
