<html>
<?php include 'shopHead.phtml'; ?>
<body>
<div class="container-fluid">
<?php include 'shopFrontNavbar.phtml'; ?>
    <div class="col-xs-10 col-xs-offset-1 checkout-container">
        <h3 class="text-center">Checkout...</h3>
        <div class="col-xs-12 col-md-6">
            <hr class="divider">
            <h4>Delivery Details</h4>
        <form id="checkout-form" action="/confirmation" method="post">
            <p>Email:</p>
            <input class="col-xs-12 required-email" id="email" type="email" name="customerEmail" required>
            <p>First Name:</p>
            <input class="col-xs-12 requiredContent" id="firstName" type="text" name="customerName" required>
            <p>Surname:</p>
            <input class="col-xs-12 requiredContent" id="surname" type="text" name="customerSurname" required>
            <p>Address:</p>
            <input class="col-xs-12 requiredCharacters" id="address" type="text" name="deliveryAddress" required>
            <p>City:</p>
            <input class="col-xs-12 requiredContent" id="city" type="text" name="deliveryCity" required>
            <p>Postcode:</p>
            <input class="col-xs-12 required-postcode" id="postcode" type="text" name="deliveryPostcode" required>
            <div class="col-xs-12 different-billing-button"><p>Add different billing address</p></div>
            <div class="different-billing">
                <p>Billing Address:</p>
                <input class="col-xs-12" id="addressBanking" type="text" name="billingAddress">
                <p>Billing City:</p>
                <input class="col-xs-12" id="cityBanking" type="text" name="billingCity">
                <p>Billing Postcode:</p>
                <input class="col-xs-12" id="postcodeBanking" type="text" name="billingPostcode">
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <hr class="divider">
            <h4>Payment Details</h4>
            <p>Name On Card:</p>
            <input class="col-xs-12 requiredContent" id="nameOnCard" type="text" name="nameOnCard" required>
            <p>Card Number: (no spaces)</p>
            <input class="col-xs-12 required-card-number" id="cardNumber" type="number" size="16" name="cardNumber" required>
            <p>CVS Number:</p>
            <input class="col-xs-12 required-cvs-number" id="cvsNumber" type="number" size="3" required>
            <p>Card Expiry:</p>
            <select class="col-xs-5 required-expiry-month">
                <option value="1">January</option>
                <option value="2">February</option>
                <option value="3">March</option>
                <option value="4">April</option>
                <option value="5">May</option>
                <option value="6">June</option>
                <option value="7">July</option>
                <option value="8">August</option>
                <option value="9">September</option>
                <option value="10">October</option>
                <option value="11">November</option>
                <option value="12">December</option>
            </select>
            <select class="col-xs-5 col-xs-offset-2 yearContent">
                <option value="2016">2016</option>
                <option value="2017">2017</option>
                <option value="2018">2018</option>
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
            </select>
        </div>
        <div class="col-xs-12 complete-order">
            <hr class="divider">
            <input class='col-xs-12 col-md-6 col-md-offset-6' type='submit' value='Complete Order'>
        </div>
        </form>
    </div>
</div>
</body>
</html>
