<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/../img/favicon.ico" type="image/x-icon">
    <title>Bookie Monster</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/shopFrontNavbar.css">
    <link rel="stylesheet" type="text/css" href="/css/shopFrontHomepage.css">
    <link rel="stylesheet" type="text/css" href="/css/shopFrontProductPage.css">
    <link rel="stylesheet" type="text/css" href="/css/unslider.css">
    <link rel="stylesheet" type="text/css" href="/css/unslider-dots.css">
    <link rel="stylesheet" type="text/css" href="/css/shopFrontBasketPage.css">
    <link rel="stylesheet" type="text/css" href="/css/shopFrontCheckout.css">
    <link rel="stylesheet" type="text/css" href="/css/shopFrontConfirmation.css">
    <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="/js/validate.js"></script>
    <script src="/js/checkout.js"></script>
</head>