<header>
        <div class="row col-xs-12 shop-front-navbar">
            <a href="/">
                <div class="col-xs-8">
                    <img src="/img/cookieMonster.png">
                    <span class="logo-text">Bookie Monster</span>
                </div>
            </a>
            <div class="col-xs-4 nav-right">
                <a href="/basket">
                    <button class="basket-Button"><img src="/img/basket_icon.png"><span
                            class="basket"><?php echo $totalItems; ?></span>
                    </button>
                </a>
            </div>
        </div>
</header>
